# Generated by Django 2.1.3 on 2018-11-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
