# Generated by Django 2.1.3 on 2018-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddi', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('ddd', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('tel', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegCli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=100)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('country', models.CharField(blank=True, max_length=70, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
