# Generated by Django 2.1.3 on 2018-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
