# Generated by Django 2.1.3 on 2018-11-02 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_phones_regcli'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='cli',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='register.RegCli'),
            preserve_default=False,
        ),
    ]
