# Generated by Django 2.1.3 on 2018-11-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_phones_cli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='cli',
        ),
    ]
