# Generated by Django 2.1.3 on 2018-11-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20181102_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='cli',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.CASCADE, related_name='RegCli', to='register.RegCli'),
        ),
    ]
